### ISSUE TITLE
插件相关建议

### ISSUE THREAD

**Issue by iamqiz** [cissusnar/cpluginscript#2]
1.建议安装插件时,支持安装服务器插件比如官方插件和开发者插件,用户只需要点击菜单就可以直接下载,
   1.1建议增加个访问网址的插件(当剪贴板内容是网址的话,就跳转)
2. 建议增加一个插件脚本编辑框, 用户直接可以编辑脚本并自动转化为插件, 避免了登录linux/下载GitHub源码/生成项目/创建脚本/打包脚本/安装本地脚本等一系列繁琐步骤;  
3.1 剪贴板每条记录显示宽度有点窄,只能看到前面一部分内容
3.2增加编辑剪贴板的功能,方便修改
   
------附上把剪贴板内容当网址进行访问的代码
function main(text)
        local txt = app.openURL(text);
        return txt
end

**Comment by cissusnar** [comment]
都是很好的建议， 大部分mac客户端已经实现了， Windows客户端后续会同步过去。 
直接打开url的插件可以在插件git repo上面直接clone一份， 把插件文件夹直接放到客户端插件目录重启客户端后就可以读取了。 
后面会增加一个重载所有插件的按钮。
